name: build

on:
  push:
    tags:
      - 'v*' # Build tagged releases

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.2'
      - name: Build
        run: |
          go build
          mv enyaq_exporter enyaq_exporter-${GITHUB_REF#refs/tags/v}-linux-amd64
          bzip2 -f enyaq_exporter-${GITHUB_REF#refs/tags/v}-linux-amd64

      - name: Upload Linux release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: enyaq_exporter-*-linux-amd64.bz2

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.2'
      - name: Build
        run: |
         GOARCH=arm64 GOOS=linux go build
          mv enyaq_exporter enyaq_exporter-${GITHUB_REF#refs/tags/v}-linux-arm64
          bzip2 -f enyaq_exporter-${GITHUB_REF#refs/tags/v}-linux-arm64

      - name: Upload Linux release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: enyaq_exporter-*-linux-arm64.bz2
